### ISSUE TITLE
whether the scalar Date can't config format in yml

### ISSUE THREAD

**Issue by weiran1999** [tailrocks/graphql-java-datetime#158]
I want to config the yml for that, but it can't go into effect.
```
graphql:
  servlet:
    mapping: /graphql
  datetime:
    scalars:
      date:
        scalar-name: MyDate
        format: yyyy-MM-dd HH:mm:ss
```
